import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSystemEventLogs1720000000001 implements MigrationInterface {
  name = "AddSystemEventLogs1720000000001";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "system_event_logs" (
        "event_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "event_type" character varying(50) NOT NULL,
        "actor_type" character varying(50),
        "actor_id" BIGINT,
        "target_type" character varying(50),
        "target_id" BIGINT,
        "request_id" character varying(80),
        "http_method" character varying(10),
        "path" character varying(255),
        "status_code" integer,
        "message" text,
        "metadata" jsonb,
        "created_at" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "system_event_logs"`);
  }
}
