import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1720000000000 implements MigrationInterface {
  name = "InitialSchema1720000000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DO $$ BEGIN CREATE TYPE "roles_role_name_enum" AS ENUM ('USER', 'ADMIN', 'MODERATOR'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
    await queryRunner.query(`DO $$ BEGIN CREATE TYPE "users_status_enum" AS ENUM ('ACTIVE', 'SUSPENDED', 'BLOCKED'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
    await queryRunner.query(`DO $$ BEGIN CREATE TYPE "advertisements_status_enum" AS ENUM ('ACTIVE', 'SOLD', 'INACTIVE', 'EXPIRED', 'HIDDEN', 'DELETED'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
    await queryRunner.query(`DO $$ BEGIN CREATE TYPE "reports_reason_enum" AS ENUM ('SPAM', 'FAKE', 'SCAM', 'DUPLICATE', 'INAPPROPRIATE', 'OTHER'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);
    await queryRunner.query(`DO $$ BEGIN CREATE TYPE "reports_status_enum" AS ENUM ('PENDING', 'REVIEWED', 'RESOLVED', 'REJECTED'); EXCEPTION WHEN duplicate_object THEN null; END $$;`);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "roles" (
        "role_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "role_name" "roles_role_name_enum" NOT NULL,
        CONSTRAINT "UQ_roles_role_name" UNIQUE ("role_name")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "locations" (
        "location_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" character varying(100) NOT NULL,
        "parent_location_id" BIGINT,
        "type" character varying(50)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "categories" (
        "category_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" character varying(100) NOT NULL,
        "icon" character varying(255),
        "description" text,
        "is_active" boolean NOT NULL DEFAULT true,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_categories_name" UNIQUE ("name")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "subcategories" (
        "subcategory_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "category_id" BIGINT NOT NULL,
        "name" character varying(100) NOT NULL,
        "description" text,
        "is_active" boolean NOT NULL DEFAULT true
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_subcategories_category') THEN
          ALTER TABLE "subcategories" ADD CONSTRAINT "FK_subcategories_category" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "users" (
        "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "full_name" character varying(150) NOT NULL,
        "phone" character varying(20) NOT NULL,
        "email" character varying(150),
        "password_hash" character varying(255) NOT NULL,
        "profile_image" character varying(500),
        "role_id" BIGINT NOT NULL,
        "location_id" BIGINT,
        "status" "users_status_enum" NOT NULL DEFAULT 'ACTIVE',
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_users_phone" UNIQUE ("phone"),
        CONSTRAINT "UQ_users_email" UNIQUE ("email")
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_users_role') THEN
          ALTER TABLE "users" ADD CONSTRAINT "FK_users_role" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_users_location') THEN
          ALTER TABLE "users" ADD CONSTRAINT "FK_users_location" FOREIGN KEY ("location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "advertisements" (
        "ad_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" BIGINT NOT NULL,
        "category_id" BIGINT NOT NULL,
        "subcategory_id" BIGINT,
        "location_id" BIGINT,
        "title" character varying(200) NOT NULL,
        "description" text NOT NULL,
        "price" numeric(12,2),
        "status" "advertisements_status_enum" NOT NULL DEFAULT 'ACTIVE',
        "view_count" integer NOT NULL DEFAULT 0,
        "contact_phone" character varying(20),
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP NOT NULL DEFAULT now(),
        "expired_at" TIMESTAMP
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ads_user') THEN
          ALTER TABLE "advertisements" ADD CONSTRAINT "FK_ads_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ads_category') THEN
          ALTER TABLE "advertisements" ADD CONSTRAINT "FK_ads_category" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ads_subcategory') THEN
          ALTER TABLE "advertisements" ADD CONSTRAINT "FK_ads_subcategory" FOREIGN KEY ("subcategory_id") REFERENCES "subcategories"("subcategory_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ads_location') THEN
          ALTER TABLE "advertisements" ADD CONSTRAINT "FK_ads_location" FOREIGN KEY ("location_id") REFERENCES "locations"("location_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "images" (
        "image_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "ad_id" BIGINT NOT NULL,
        "image_url" character varying(500) NOT NULL,
        "thumbnail_url" character varying(500),
        "is_main" boolean NOT NULL DEFAULT false,
        "uploaded_at" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_images_ad') THEN
          ALTER TABLE "images" ADD CONSTRAINT "FK_images_ad" FOREIGN KEY ("ad_id") REFERENCES "advertisements"("ad_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "favorites" (
        "favorite_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" BIGINT NOT NULL,
        "ad_id" BIGINT NOT NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_favorites_user_ad" UNIQUE ("user_id", "ad_id")
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_favorites_user') THEN
          ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_favorites_ad') THEN
          ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_ad" FOREIGN KEY ("ad_id") REFERENCES "advertisements"("ad_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "reports" (
        "report_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "reporter_user_id" BIGINT NOT NULL,
        "ad_id" BIGINT NOT NULL,
        "reason" "reports_reason_enum" NOT NULL,
        "comment" text,
        "status" "reports_status_enum" NOT NULL DEFAULT 'PENDING',
        "created_at" TIMESTAMP NOT NULL DEFAULT now(),
        "reviewed_at" TIMESTAMP,
        "reviewed_by" BIGINT,
        CONSTRAINT "UQ_reports_user_ad" UNIQUE ("reporter_user_id", "ad_id")
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_reports_reporter') THEN
          ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_reporter" FOREIGN KEY ("reporter_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_reports_ad') THEN
          ALTER TABLE "reports" ADD CONSTRAINT "FK_reports_ad" FOREIGN KEY ("ad_id") REFERENCES "advertisements"("ad_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "admin_action_logs" (
        "log_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "admin_user_id" BIGINT NOT NULL,
        "action_type" character varying(50) NOT NULL,
        "target_type" character varying(50) NOT NULL,
        "target_id" BIGINT NOT NULL,
        "description" text,
        "created_at" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_admin_action_logs_admin_user') THEN
          ALTER TABLE "admin_action_logs" ADD CONSTRAINT "FK_admin_action_logs_admin_user" FOREIGN KEY ("admin_user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "admin_action_logs" DROP CONSTRAINT IF EXISTS "FK_admin_action_logs_admin_user"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "admin_action_logs"`);

    await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT IF EXISTS "FK_reports_reporter"`);
    await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT IF EXISTS "FK_reports_ad"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "reports"`);

    await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT IF EXISTS "FK_favorites_user"`);
    await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT IF EXISTS "FK_favorites_ad"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "favorites"`);

    await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT IF EXISTS "FK_images_ad"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "images"`);

    await queryRunner.query(`ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "FK_ads_user"`);
    await queryRunner.query(`ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "FK_ads_category"`);
    await queryRunner.query(`ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "FK_ads_subcategory"`);
    await queryRunner.query(`ALTER TABLE "advertisements" DROP CONSTRAINT IF EXISTS "FK_ads_location"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "advertisements"`);

    await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "FK_users_role"`);
    await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "FK_users_location"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users"`);

    await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT IF EXISTS "FK_subcategories_category"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "subcategories"`);

    await queryRunner.query(`DROP TABLE IF EXISTS "categories"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "locations"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "roles"`);

    await queryRunner.query(`DROP TYPE IF EXISTS "reports_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "reports_reason_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "advertisements_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "users_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "roles_role_name_enum"`);
  }
}
